# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7409f41ef6d4b8d15e3a6ebaf3168db5d69ce4a043e66dea8120c727ca3e4029e23e9865d443026f8089e4780f8f23c231e0ba209d9e109b4249376cb471b4dd

test:
  secret_key_base: 633f38e15299baa6d8cf2b082d3c99436190cb94370045c63b7c1fe98f968c654d1c052ba4754335bce96d21d56d0a44e6ac19169e7be03188ff6bfc371f716e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
